### ISSUE TITLE
nice, just tried it out

### ISSUE THREAD

**Issue by ToJen** [dylanon/dark-mode-chrome-extension#3]
i've been wondering why this isn't supported by default on chrome for a while now.

**Comment by dylanon** [comment]
> i've been wondering why this isn't supported by default on chrome for a while now.

Thanks for trying it out - I think people would be pretty frustrated if Chrome endorsed messing with web pages in this way 😅

**Comment by ToJen** [comment]
haha, true true. anyways good luck with the project :+1:
